### ISSUE TITLE
Thrasher Crashes Servers

### ISSUE THREAD

**Issue by InteJason** [team-abnormals/upgrade-aquatic#291] opened 2021-08-29 15:42 UTC
https://pastebin.com/dPnGU3rH

**Comment by SmellyModder** [comment] 2021-09-05 01:01
This is a weird crash report.
When does this crash happen?
From the looks of it, this crash could have only happened if the Thrasher was riding itself.

**Comment by SmellyModder** [comment] 2021-09-05 04:34
There is actually a duplicate of #265

**Closed by SmellyModder** 2021-09-05 04:34 UTC
Labels: Bug?
